# -*- coding: utf-8 -*-
"""Workshop 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFQ_D8YNFHs8b8jJPfCj8UYCpQOGYk0j
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install obspy

from obspy import read

st = read()
st[1].plot()