# -*- coding: utf-8 -*-
"""Workshop 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFQ_D8YNFHs8b8jJPfCj8UYCpQOGYk0j
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install obspy

from obspy import read

st = read() #อ่านไฟล์
st[1].plot() #เลือกเฉพาะคลื่นที่เราต้องการ
st[1].spectrogram(log=True) #ปรับคลื่นความถี่กับspectrography

# Filter the wave form
tr = st[1].copy()
tr.filter('bandpass', freqmin=1.0, freqmax=5.0, corners=4, zerophase=True)
tr.plot()

tr.write("demo_eq.mseed", format='MSEED')

fig =  tr.plot(show=False)
fig.savefig('demo_waveform.png', dpi=300)